//! Main Strings
import 'dart:html';

const appName = "Peeps",
    credits = "@pavin__das",
    appversion = "Version 1.0.0",

//! Home Strings
    Welcome = "Welcome",
    name = "Name",
    nameHint = "Your Name",
    email = "Email",
    phone = "Phone",
    phoneHint = "+91 9876543210",
    emailHint = "admin@admin.com",
    enterEmail = "Enter your email address",
    password = "Password",
    passwordHint = "******",
    enterPass = "Enter your password",
    retypePass = "Confirm Password",
    forgetPass = "Forget Password",
    enterusernames = "Enter your username",
    enterBio = "Enter your bio",
    login = "Log In",
    signup = "Sign Up",
    createNewAccount = "or, Create a new account?",
    dontHaveAcc = "Don't have an account?",
    loginWith = "Log In with",
    logout = "Log Out",
    privacyPolicy = "Privacy Policy",
    termsCond = "Terms and Condition",
    alreadyHaveAcc = "Already have an account? ",
    buyYourFav = "Buy Your Favorites",
    welcomeBack = "Welcome Back",
    createNewAcc = "Create An Account",
    loading = "Loading...",
    emptyMail = "Email is empty",
    emptyPass = "Password is empty",
    emptyName = "Name is empty",
    emptyPhone = "Phone number is empty",
    enterDetails = "Enter details",
    cancel = "Cancel",
    home = "Home",
    edit = "Edit",
    explore = "Explore",
    search = "Search",
    postTo = "Post to",
    createPost = "Create a post",
    takePhoto = "Take a photo",
    choosePhoto = "Choose a photo",
    download = "Download",
    downloadNow = "Download Now",
    like = "Like",
    Comment = "Comment",
    share = "Share",
    save = "Save",

    //! Account Strings
    myAccount = "My Account",
    editProfile = "Edit Profile",
    favorites = "Favorites",
    yourFavoriteIsEmpty = "Your Favorites is Empty",
    account = "Account";
